// 04-db-app-2/mf-cards/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: mf-cards</div>
    <div>Framework: vue3</div>
    <cards></cards>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Cards from "./components/Cards.vue";

export default defineComponent({
  components: { Cards },
});
</script>

// 04-db-app-2/mf-character-details/src/App.tsx
import ReactDOM from "react-dom/client";

import "./index.css";
import CharacterDetails from "./components/CharacterDetails";

const App = () => (
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: mf-character-details</div>
    <div>Framework: react-19</div>
    <CharacterDetails />
  </div>
);

const root = ReactDOM.createRoot(document.getElementById("app") as HTMLElement);

root.render(<App />);
